name: Build

on:
  push:
    branches: 
    - master
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  build-oci:
    name: build container image
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - id: setup-pack
        uses: buildpacks/github-actions/setup-pack@v4.1.0
      - id: package
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          pack build --builder ${BUILDER} --publish ${IMAGE}
        shell: bash
        env:
          BUILDER: gcr.io/buildpacks/builder:v1
          IMAGE: ghcr.io/${{ github.repository_owner }}/coscup2021-tw-sample-go
